#!/usr/bin/env python3
"""Rebuild js/assets.js from audio/*.mp3 (embedded so the game also works from a file).

  python3 tools/make_assets.py                     -> re-embed audio/
  python3 tools/make_assets.py --lines CLIP.mp3     -> split a clip of the tuxedo men's three lines
                                                     (separated by ~2 s of silence) into audio/line_*.mp3 first
Needs ffmpeg (pip install imageio-ffmpeg) and numpy for --lines.
"""
import base64, os, subprocess, sys, tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AUDIO = os.path.join(ROOT, 'audio')
ORDER = ['piano', 'vocals', 'full', 'no', 'line_hey', 'line_said', 'line_letgo']


def ffmpeg():
    try:
        import imageio_ffmpeg
        return imageio_ffmpeg.get_ffmpeg_exe()
    except ImportError:
        return 'ffmpeg'


def split_lines(clip):
    import numpy as np, wave
    ff = ffmpeg()
    tmp = tempfile.mktemp(suffix='.wav')
    subprocess.run([ff, '-y', '-loglevel', 'error', '-i', clip, '-ac', '1', '-ar', '44100', tmp], check=True)
    with wave.open(tmp) as w:
        sr = w.getframerate(); x = np.frombuffer(w.readframes(w.getnframes()), dtype=np.int16).astype(float)
    x /= max(1.0, np.abs(x).max())
    hop = int(sr * 0.02)
    env = np.array([np.sqrt((x[i:i + hop] ** 2).mean()) for i in range(0, len(x) - hop, hop)])
    loud = env > max(0.02, env.max() * 0.06)
    # group loud frames, merging gaps shorter than 0.6 s (pauses inside a sentence)
    segs, start, quiet = [], None, 0
    for i, on in enumerate(loud):
        if on:
            if start is None: start = i
            quiet = 0
        elif start is not None:
            quiet += 1
            if quiet * 0.02 >= 0.6:
                segs.append((start, i - quiet + 1)); start = None; quiet = 0
    if start is not None: segs.append((start, len(loud)))
    segs = [s for s in segs if (s[1] - s[0]) * 0.02 > 0.12]
    if len(segs) != 3:
        sys.exit('expected 3 voice lines separated by silence, found %d: %s' % (len(segs), [(round(a * .02, 2), round(b * .02, 2)) for a, b in segs]))
    for name, (a, b) in zip(['line_hey', 'line_said', 'line_letgo'], segs):
        t0, t1 = max(0, a * 0.02 - 0.08), b * 0.02 + 0.15
        out = os.path.join(AUDIO, name + '.mp3')
        subprocess.run([ff, '-y', '-loglevel', 'error', '-i', tmp, '-af',
                        'atrim=start=%.3f:end=%.3f,asetpts=PTS-STARTPTS,loudnorm=I=-16:TP=-1.5,afade=t=out:st=%.3f:d=0.12' % (t0, t1, t1 - t0 - 0.12),
                        '-ac', '1', '-ar', '44100', '-b:a', '96k', out], check=True)
        print('%s: %.2fs - %.2fs' % (name, t0, t1))
    os.remove(tmp)


def embed():
    js = '/* generated by tools/make_assets.py: embedded audio so the game also works when opened from a file */\nwindow.ASSETS={\n'
    for k in ORDER:
        p = os.path.join(AUDIO, k + '.mp3')
        if os.path.exists(p):
            js += ' %s:"data:audio/mpeg;base64,%s",\n' % (k, base64.b64encode(open(p, 'rb').read()).decode())
    open(os.path.join(ROOT, 'js', 'assets.js'), 'w').write(js + '};\n')
    print('wrote js/assets.js')


if __name__ == '__main__':
    if len(sys.argv) > 2 and sys.argv[1] == '--lines':
        split_lines(sys.argv[2])
    embed()
